CREATE TABLE jogador (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    clube_id BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

ALTER TABLE jogador ADD CONSTRAINT fk_clube FOREIGN KEY (clube_id) REFERENCES clube(id)